name: Tests API

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./meeting-bot-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest app/tests/